import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";

const SarabunFont = Sarabun({
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en,th">
      <body className={`${SarabunFont.className} ${SarabunFont.className}`}>
        {children}
      </body>
    </html>
  );
}
